### ISSUE TITLE
Remove Arcade?

### ISSUE THREAD

**Issue by wtl420** [Jaxboards/Jaxboards#3]
The arcade is based on flash games, and as we know, Flash is on its way out. In addition, the Arcade had to be enabled on specific boards on the original JaxBoards service, so I don't think it's that much of a special feature.

**Comment by wtl420** [comment]
I removed the games, looks like the arcade page code calls a table that doesn't exist as far as I know? So the arcade might as well be useless regardless if it's used or not.

**Comment by seanjohnson08** [comment]
Yes, I agree. Let's remove the arcade. I never really finished it (or even enabled it for all forums) - and as you mentioned, flash games in 2018 is not a good mix.
