### ISSUE TITLE
Replace things that rely on Flash

### ISSUE THREAD

**Issue by wtl420** [Jaxboards/Jaxboards#7]
The uploader and sounds (and Arcade, but see #3 for that) rely on Flash; I don't think anything else does. These can be done with regular old HTML5/JavaScript these days, we just need to update JaxBoards to do it that way.

**Comment by seanjohnson08** [comment]
I migrated Sounds from using Flash in this commit: https://github.com/Jaxboards/Jaxboards/commit/79426e5ac66a32d85c2838dde7c8861a2f04dc53
